language: python
cache: pip
sudo: false
env:
  global:
  - PACKAGENAME="rohan"
  - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
python:
- 3.6
before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- echo $MINICONDA_URL
- wget $MINICONDA_URL -O miniconda.sh;
- bash miniconda.sh -b -f -p $MINICONDA;
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda env create -f environment.yml
- source activate rohan
install:
- python setup.py install --record installed_files.txt
script:
- python test/test_install.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: rraadd88
  distributions: sdist bdist_wheel
  password:
    secure: CQLuuSQ8pTiO/AXT39dYdkKCD8BEl7gvgjch2kyduL2gYNU/dxWrkDfK338L6oZVR4WSeb95lYmcltL70peCfdj1L7bVg69MxbxhWt+b+aJ4K9od+sqAecmWc0z0S7FqwSZA3UMmAnVThPZjUmKVZh+k4CFLFVjINj6JlD3mk5ECiShLMbUUg8O+6LDe6JSLQhY3QZ9SO1zpQGfxNMCgYoKTBfu7+Qfp5EpYRxfD5oH+eM6U7wavRSMnNOFkhJfMqa0tAbVucEjED4XNd6vT+uSzVDIvJwImJnQ5BjjUO94MNgOcd2mIonbebQt2/5Ab69r66LCnh1IzTryMVYAyPfoGwlTEw8c6UrmD6W5YIz6aqMfByYUAXrdgUBlYbnURHAaI+wgPQDvKKTraENFadL7pYsIhU3E9aYjiBfA+6Mkxyjpj8k4fZjGxbOduI3P02qbKEs8IpVyDcPhgHYiYNH/EWzL/7is/rUbkhHKb8dDooF6iRnPNS4OVo90krOzcVzTW6Oozev1En81LXBgNrqv0Dx4oEH2TXQkt1ai3ND5AIHaKZ77dIPyuIIJgmks0e3XZ172EbGQG+y6nVzUL+9WsuBeDKLcykQfH62ZVRr83uGieuG1A6To3KSxmvy84IkQB6eGPeGOIumkaCqOhrz/gEmQNchWvM5cteP4ckeg=
  # on:
  #   tags: true
  #   branch: master  
