language: python
cache: pip
sudo: false
env:
  global:
  - PACKAGENAME="rohan"
  - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
python:
- 3.6
before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- echo $MINICONDA_URL
- wget $MINICONDA_URL -O miniconda.sh;
- bash miniconda.sh -b -f -p $MINICONDA;
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda env create -f environment.yml
- source activate rohan
install:
- python setup.py install --record installed_files.txt
script:
- python test/test_install.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: rraadd88
  distributions: sdist bdist_wheel
  password:
    secure: "LnFrWTr9wqrXUp+i4VEUPDmEp2BiizuFxvPmPEwH6GcisoXSQ/qpyEPr3yPN4D5+m2mz5I9VrHi5AIQKlAJqiqJ+o21HuQQS/dgF7EzpKutPKmrVmtozluzuXE2j7O6Umxee5o7QlOBy6K5H8Pl5WaZtFHrVWtWEExe+wPKisjCZE54n4m321tNL0HYj3gGKXTkUaY/WSyYOJaN2/B1UDrFunGaFjSUG9UcSyS86khxb450GDv/P+9sCBeSfSLakTkC0yIOt23yHcSLbytrXIGiQszqhMcj0CQqTdEOywg0K33Nz7EjWjrYbfMBUGh892bv0abVyFv2pZGJPGF/i2PZfmAOwGyV2bUjK+1uCpl9Z5P6/eOWiudH6vzJYwuqvHmlkGjSiTqOxRNx58WQZfeUTjY1uXF1s0MpU/5qMadyaoJAyq1UuGG3oHnyksBQKWXcxrOviBVE1OTfSYcUZLBqcXLJ8XypiL+j6jN1Sj6mwy1UkiCE9aryZYoKPNJL1c9qNhUDa4NMovtJVO/1EqGyY1qFHGEiI369BHgTd8dGQxxYcPl+W5q13rDnLCkvdaUC1UpuXTuZvZC+HBh/rYLnS0nskfLr/F1X9RPEuKc8x0VeH5SzOuTb+AG0aX3LgwCecNy1cLm49rOA6V6jN4z8DJMOk5CqQZb2Lykfh26g="
  on:
     tags: true
     branch: master  
