name: rohan
channels:
  - conda-forge
  - biocore
  - bioconda 
dependencies:
  - biopython>=1.71
  - numpy
  - python=3.6.5
  - setuptools=39.2.0
  - pyyaml
  - pip:
    - matplotlib>=2.2
    - requests==2.19.1
    - scipy>=1.1.0
    - tqdm==4.23.4
    - seaborn>=0.8
    - pandas>=0.23
    - fastparquet
    - fastcluster
    - xlrd
    - pingouin
